image:
  file: .gitpod.dockerfile

tasks:
    - before: nvm install 18.16.1 && nvm use 18.16.1
      init: npm install
      command: npm run start-server

ports:
    - port: 8080
      onOpen: open-preview
